# Default values for python.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 10.63.252.88:5000/anners/translate-fe
  tag: 0.0.10
  pullPolicy: IfNotPresent
service:
  name: translate-fe
  type: ClusterIP
  externalPort: 80
  internalPort: 5002
  annotations:
    fabric8.io/expose: "true"
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: false
metadata:
  tier: fe
secret:
  keyName: gcp-key
  secretName: translate-key
  mountPath: /var/secrets/gcp
  keyPath: /var/secrets/gcp/key.json
