apiVersion: apps/v1
kind: Deployment
metadata:
  name: translate-fe
  labels:
    app: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
      tier: fe
      track: dev
  template:
    metadata:
      labels:
        app: hello-world
        tier: fe
        track: dev
    spec:
      volumes:
      - name: gcp-key
        secret:
          secretName: translate-key
      containers:
      - name: hello-world-fe
        image: anners/translate-fe
        livenessProbe:
          periodSeconds: 5
          initialDelaySeconds: 2
          httpGet:
            path: /health
            port: 5002
        ports:
        - containerPort: 5002
        volumeMounts:
        - name: gcp-key
          mountPath: /var/secrets/gcp
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/gcp/key.json
