apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: translate-fe
  labels:
    app: hello-world
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
        tier: fe
        track: dev
    spec:
      containers:
      - name: hello-world-fe
        image: anners/translate-fe:latest
        livenessProbe:
          periodSeconds: 5
          initialDelaySeconds: 2
          httpGet:
            path: /health
            port: 5002
        ports:
        - containerPort: 5002
